# Generated by Django 4.2.3 on 2023-07-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_articulos_delete_carrito'),
    ]

    operations = [
    ]
